services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/srv/public:rw,cached
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: "${BUILD_TARGET:-app}"
    volumes:
      - ./app:/srv
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      host.docker.internal: host-gateway
  db:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-sf_project_1}sys

  cache:
    image: redis:latest

volumes:
  postgres_data: ~