services:
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/srv/public:rw,cached
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app
  db:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped # replace with always in production
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-sf_project_1}

volumes:
  postgres_data: ~
